(deftheme darkokai-custom
  "Created 2017-02-23.")

(custom-theme-set-variables
 'darkokai-custom
 '(ansi-color-names-vector ["#242728" "#ff0066" "#63de5d" "#E6DB74" "#06d8ff" "#ff8eff" "#53f2dc" "#f8fbfc"])
 '(compilation-message-face (quote default)))

(custom-theme-set-faces
 'darkokai-custom
 '(font-lock-builtin-face ((((class color) (min-colors 257)) (:foreground "#ff0066" :weight normal)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight normal))))
 '(font-lock-comment-delimiter-face ((t (:foreground "gray"))))
 '(font-lock-comment-face ((t (:foreground "gray"))))
 '(font-lock-constant-face ((((class color) (min-colors 257)) (:foreground "#ab7eff")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(font-lock-doc-face ((t (:foreground "gray"))))
 '(font-lock-function-name-face ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(font-lock-keyword-face ((((class color) (min-colors 257)) (:foreground "#ff0066" :weight normal)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight normal))))
 '(font-lock-negation-char-face ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 257)) (:foreground "#ff0066")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 257)) (:foreground "#ab7eff" :weight normal)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :weight normal))))
 '(font-lock-string-face ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(font-lock-type-face ((((class color) (min-colors 257)) (:foreground "#06d8ff" :italic nil)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :italic nil))))
 '(font-lock-variable-name-face ((((class color) (min-colors 257)) (:foreground "#ffac4a")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(font-lock-warning-face ((((class color) (min-colors 257)) (:foreground "#ffac4a" :weight bold :italic t :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold :italic t :underline t))))
 '(c-annotation-face ((((class color) (min-colors 257)) (:inherit font-lock-constant-face)) (((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(button ((t (:underline t))))
 '(highlight ((((class color) (min-colors 257)) (:foreground "#242728" :background "#5D6365")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F4A460"))))
 '(lazy-highlight ((((class color) (min-colors 257)) (:inherit highlight :background "#6A6D70")) (((class color) (min-colors 89)) (:inherit highlight :background "#8B8878"))))
 '(region ((((class color) (min-colors 257)) (:inherit highlight :background "#5D6365")) (((class color) (min-colors 89)) (:inherit highlight :background "#F4A460"))))
 '(secondary-selection ((((class color) (min-colors 257)) (:inherit region :background "#06d8ff")) (((class color) (min-colors 89)) (:inherit region :background "#5FD7FF"))))
 '(shadow ((t (:foreground "gray"))))
 '(match ((((class color) (min-colors 257)) (:foreground "#BBF7EF" :background "#00b2ac" :weight bold)) (((class color) (min-colors 89)) (:background "#AFFFFF" :foreground "#5FAFAF" :weight bold))))
 '(cursor ((((class color) (min-colors 257)) (:foreground "#242728" :background "#f8fbfc" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(mouse ((((class color) (min-colors 257)) (:foreground "#242728" :background "#f8fbfc" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(escape-glyph ((t (:foreground "gray"))))
 '(fringe ((((class color) (min-colors 257)) (:foreground "#f8fbfc" :background "#242728")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#3D3D3D"))))
 '(link ((((class color) (min-colors 257)) (:foreground "#06d8ff" :underline t :weight bold)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 257)) (:foreground "#ab7eff" :underline t :weight normal)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :underline t :weight normal))))
 '(success ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(warning ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(error ((((class color) (min-colors 257)) (:foreground "#FF6159")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(trailing-whitespace ((((class color) (min-colors 257)) (:background "#ff0066")) (((class color) (min-colors 89)) (:background "#FF1493"))))
 '(vertical-border ((t (:foreground "dark gray"))))
 '(menu ((((class color) (min-colors 257)) (:foreground "#f8fbfc" :background "#242728")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(minibuffer-prompt ((((class color) (min-colors 257)) (:foreground "#C9ACFF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(mode-line ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#f8fbfc" :background "#35393b" :box (:line-width 8 :color "#35393b" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#F5F5F5" :background "#3D3D3D"))))
 '(mode-line-buffer-id ((((class color) (min-colors 257)) (:foreground "#63de5d" :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(mode-line-inactive ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#6A6D70" :background "#242728" :box (:line-width 8 :color "#242728" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#8B8878" :background "#1B1E1C"))))
 '(header-line ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#ffffff" :background "#424748" :box (:line-width 1 :color "#35393b" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#FFFAFA" :background "#474747" :box (:line-width 1 :color "#3D3D3D" :style unspecified)))))
 '(diary ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(dired-directory ((((class color) (min-colors 257)) (:foreground "#06d8ff")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(dired-flagged ((((class color) (min-colors 257)) (:foreground "#ff0066")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(dired-header ((((class color) (min-colors 257)) (:foreground "#06d8ff" :background "#242728" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :background "#1B1E1C" :inherit bold))))
 '(dired-ignored ((((class color) (min-colors 257)) (:inherit shadow)) (((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 257)) (:foreground "#63de5d" :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(dired-marked ((((class color) (min-colors 257)) (:foreground "#ab7eff" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :inherit bold))))
 '(dired-perm-write ((((class color) (min-colors 257)) (:foreground "#f8fbfc" :underline t)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :underline t))))
 '(dired-symlink ((((class color) (min-colors 257)) (:foreground "#53f2dc" :slant italic)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :slant italic))))
 '(dired-warning ((((class color) (min-colors 257)) (:foreground "#ffac4a" :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :underline t))))
 '(isearch ((((class color) (min-colors 257)) (:foreground "#BBF7EF" :background "#00b2ac")) (((class color) (min-colors 89)) (:foreground "#AFFFFF" :background "#5FAFAF"))))
 '(isearch-fail ((((class color) (min-colors 257)) (:inherit isearch :foreground "#ff0066" :background "#242728" :bold t)) (((class color) (min-colors 89)) (:inherit isearch :foreground "#FF1493" :background "#1B1E1C" :bold t))))
 '(font-latex-bold-face ((((class color) (min-colors 257)) (:inherit bold :foreground "#ffffff")) (((class color) (min-colors 89)) (:inherit bold :foreground "#FFFAFA"))))
 '(font-latex-doctex-documentation-face ((((class color) (min-colors 257)) (:background unspecified)) (((class color) (min-colors 89)) (:background unspecified))))
 '(font-latex-doctex-preprocessor-face ((((class color) (min-colors 257)) (:inherit (font-latex-doctex-documentation-face font-lock-builtin-face font-lock-preprocessor-face))) (((class color) (min-colors 257)) (:inherit (font-latex-doctex-documentation-face font-lock-builtin-face font-lock-preprocessor-face)))))
 '(font-latex-italic-face ((((class color) (min-colors 257)) (:inherit italic :foreground "#ffffff")) (((class color) (min-colors 89)) (:inherit italic :foreground "#FFFAFA"))))
 '(font-latex-math-face ((((class color) (min-colors 257)) (:foreground "#ab7eff")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(font-latex-sectioning-0-face ((((class color) (min-colors 257)) (:inherit font-latex-sectioning-1-face :height 1.1)) (((class color) (min-colors 89)) (:inherit font-latex-sectioning-1-face :height 1.1))))
 '(font-latex-sectioning-1-face ((((class color) (min-colors 257)) (:inherit font-latex-sectioning-2-face :height 1.1)) (((class color) (min-colors 89)) (:inherit font-latex-sectioning-2-face :height 1.1))))
 '(font-latex-sectioning-2-face ((((class color) (min-colors 257)) (:inherit font-latex-sectioning-3-face :height 1.1)) (((class color) (min-colors 89)) (:inherit font-latex-sectioning-3-face :height 1.1))))
 '(font-latex-sectioning-3-face ((((class color) (min-colors 257)) (:inherit font-latex-sectioning-4-face :height 1.1)) (((class color) (min-colors 89)) (:inherit font-latex-sectioning-4-face :height 1.1))))
 '(font-latex-sectioning-4-face ((((class color) (min-colors 257)) (:inherit font-latex-sectioning-5-face :height 1.1)) (((class color) (min-colors 89)) (:inherit font-latex-sectioning-5-face :height 1.1))))
 '(font-latex-sectioning-5-face ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:inherit variable-pitch : foreground "#CDC673" :weight bold))))
 '(font-latex-sedate-face ((((class color) (min-colors 257)) (:foreground "#ffffff")) (((class color) (min-colors 89)) (:foreground "#FFFAFA"))))
 '(font-latex-slide-title-face ((((class color) (min-colors 257)) (:inherit (variable-pitch font-lock-type-face) :weight bold :height 1.2)) (((class color) (min-colors 89)) (:inherit (variable-pitch font-lock-type-face) :weight bold :height 1.2))))
 '(font-latex-string-face ((((class color) (min-colors 257)) (:foreground "#53f2dc")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(font-latex-subscript-face ((((class color) (min-colors 257)) (:height 0.8)) (((class color) (min-colors 89)) (:height 0.8))))
 '(font-latex-superscript-face ((((class color) (min-colors 257)) (:height 0.8)) (((class color) (min-colors 89)) (:height 0.8))))
 '(font-latex-verbatim-face ((((class color) (min-colors 257)) (:inherit fixed-pitch :foreground "#f8fbfc" :slant italic)) (((class color) (min-colors 89)) (:inherit fixed-pitch :foreground "#F5F5F5" :slant italic))))
 '(font-latex-warning-face ((((class color) (min-colors 257)) (:inherit bold :foreground "#ffac4a")) (((class color) (min-colors 89)) (:inherit bold :foreground "#FF8C00"))))
 '(cfw:face-day-title ((((class color) (min-colors 257)) (:background "#424748")) (((class color) (min-colors 89)) (:background "#474747"))))
 '(cfw:face-annotation ((((class color) (min-colors 257)) (:inherit cfw:face-day-title :foreground "#E6DB74")) (((class color) (min-colors 89)) (:inherit cfw:face-day-title :foreground "#CDC673"))))
 '(cfw:face-default-content ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(cfw:face-default-day ((((class color) (min-colors 257)) (:inherit cfw:face-day-title :weight bold)) (((class color) (min-colors 89)) (:inherit cfw:face-day-title :weight bold))))
 '(cfw:face-disable ((((class color) (min-colors 257)) (:inherit cfw:face-day-title :foreground "#6A6D70")) (((class color) (min-colors 89)) (:inherit cfw:face-day-title :foreground "#8B8878"))))
 '(cfw:face-grid ((t (:foreground "gray"))))
 '(cfw:face-header ((((class color) (min-colors 257)) (:foreground "#CAF5FD" :background "#1DB4D0" :weight bold)) (((class color) (min-colors 89)) (:foreground "#008787" :background "#87D7FF" :weight bold))))
 '(cfw:face-holiday ((((class color) (min-colors 257)) (:background nil :foreground "#ff0066" :weight bold)) (((class color) (min-colors 89)) (:background nil :foreground "#FF1493" :weight bold))))
 '(cfw:face-periods ((((class color) (min-colors 257)) (:foreground "#ff8eff")) (((class color) (min-colors 89)) (:foreground "#D700D7"))))
 '(cfw:face-select ((((class color) (min-colors 257)) (:background "#F309DF" :foreground "#FEC6F9")) (((class color) (min-colors 89)) (:background "#FF87DF" :foreground "#AF0087"))))
 '(cfw:face-saturday ((((class color) (min-colors 257)) (:foreground "#D3FBF6" :background "#4BBEAE")) (((class color) (min-colors 89)) (:foreground "#5FAFAF" :background "#AFFFFF"))))
 '(cfw:face-sunday ((((class color) (min-colors 257)) (:foreground "#FEB0CC" :background "#F20055" :weight bold)) (((class color) (min-colors 89)) (:foreground "#870000" :background "#FF5F87" :weight bold))))
 '(cfw:face-title ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#E6DB74" :weight bold :height 1.3)) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#CDC673" :weight bold :height 1.3))))
 '(cfw:face-today ((((class color) (min-colors 257)) (:weight bold :background "#424748" :foreground nil)) (((class color) (min-colors 89)) (:weight bold :background "#474747" :foreground nil))))
 '(cfw:face-today-title ((((class color) (min-colors 257)) (:background "#9A8F21" :foreground "#FFFACE" :weight bold)) (((class color) (min-colors 89)) (:background "#FFFF87" :foreground "#878700" :weight bold))))
 '(cfw:face-toolbar ((((class color) (min-colors 257)) (:background "#424748" :foreground "#f8fbfc")) (((class color) (min-colors 89)) (:background "#474747" :foreground "#F5F5F5"))))
 '(cfw:face-toolbar-button-off ((((class color) (min-colors 257)) (:background "#9A8F21" :foreground "#FFFACE" :weight bold)) (((class color) (min-colors 89)) (:background "#FFFF87" :foreground "#878700" :weight bold))))
 '(cfw:face-toolbar-button-on ((((class color) (min-colors 257)) (:background "#FFFACE" :foreground "#9A8F21" :weight bold)) (((class color) (min-colors 89)) (:background "#878700" :foreground "#FFFF87" :weight bold))))
 '(company-tooltip ((((class color) (min-colors 257)) (:background "#424748" :foreground "#ffffff")) (((class color) (min-colors 89)) (:background "#474747" :foreground "#FFFAFA"))))
 '(company-tooltip-selection ((((class color) (min-colors 257)) (:background "#00b2ac" :foreground "#BBF7EF")) (((class color) (min-colors 89)) (:background "#5FAFAF" :foreground "#AFFFFF"))))
 '(company-tooltip-mouse ((((class color) (min-colors 257)) (:background "#06d8ff" :foreground "#242728")) (((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C"))))
 '(company-tooltip-common ((((class color) (min-colors 257)) (:foreground "#ab7eff" :underline t)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :underline t))))
 '(company-tooltip-common-selection ((((class color) (min-colors 257)) (:foreground "#f8fbfc" :background "#00b2ac" :underline t)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#5FAFAF" :underline t))))
 '(company-preview ((((class color) (min-colors 257)) (:background "#424748" :foreground "#ffffff")) (((class color) (min-colors 89)) (:background "#474747" :foreground "#FFFAFA"))))
 '(company-preview-common ((((class color) (min-colors 257)) (:foreground "#06d8ff" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))
 '(company-scrollbar-bg ((((class color) (min-colors 257)) (:background "#35393b")) (((class color) (min-colors 89)) (:background "#3D3D3D"))))
 '(company-scrollbar-fg ((((class color) (min-colors 257)) (:background "#6A6D70")) (((class color) (min-colors 89)) (:background "#8B8878"))))
 '(company-tooltip-annotation ((((class color) (min-colors 257)) (:foreground "#ffac4a")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(company-template-field ((((class color) (min-colors 257)) (:background "#424748" :foreground "#06d8ff")) (((class color) (min-colors 89)) (:background "#474747" :foreground "#5FD7FF"))))
 '(compilation-column-number ((((class color) (min-colors 257)) (:inherit font-lock-doc-face :foreground "#53f2dc" :underline nil)) (((class color) (min-colors 89)) (:inherit font-lock-doc-face :foreground "#5FFFFF" :underline nil))))
 '(compilation-error ((((class color) (min-colors 257)) (:inherit error :underline nil)) (((class color) (min-colors 89)) (:inherit error :underline nil))))
 '(compilation-info ((t (:foreground "gray" :underline nil :weight normal))))
 '(compilation-line-number ((((class color) (min-colors 257)) (:foreground "#63de5d" :underline nil)) (((class color) (min-colors 89)) (:foreground "#87D700" :underline nil))))
 '(compilation-warning ((((class color) (min-colors 257)) (:inherit warning :underline nil)) (((class color) (min-colors 89)) (:inherit warning :underline nil))))
 '(compilation-mode-line-exit ((((class color) (min-colors 257)) (:inherit compilation-info :foreground "#63de5d" :weight bold)) (((class color) (min-colors 89)) (:inherit compilation-info :foreground "#87D700" :weight bold))))
 '(compilation-mode-line-fail ((((class color) (min-colors 257)) (:inherit compilation-error :foreground "#ff0066" :weight bold)) (((class color) (min-colors 89)) (:inherit compilation-error :foreground "#FF1493" :weight bold))))
 '(compilation-mode-line-run ((((class color) (min-colors 257)) (:foreground "#ffac4a" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold))))
 '(custom-face-tag ((((class color) (min-colors 257)) (:inherit variable-pitch :height 1.2 :foreground "#ab7eff" :weight bold)) (((class color) (min-colors 89)) (:inherit variable-pitch :height 1.2 :foreground "#AF87FF" :weight bold))))
 '(custom-variable-tag ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#53f2dc" :height 1.2)) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FFFFF" :height 1.2))))
 '(custom-comment-tag ((t (:foreground "gray"))))
 '(custom-group-tag ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#06d8ff" :height 1.2)) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FD7FF" :height 1.2))))
 '(custom-group-tag-1 ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#ff0066" :height 1.2)) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#FF1493" :height 1.2))))
 '(custom-state ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(diff-added ((((class color) (min-colors 257)) (:foreground "#2AD043" :background "#242728")) (((class color) (min-colors 89)) (:foreground "#87D700" :background "#1B1E1C"))))
 '(diff-changed ((((class color) (min-colors 257)) (:foreground "#06d8ff" :background "#242728")) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :background "#1B1E1C"))))
 '(diff-removed ((((class color) (min-colors 257)) (:foreground "#FF6159" :background "#242728")) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C"))))
 '(diff-header ((((class color) (min-colors 257)) (:background "#242728")) (((class color) (min-colors 89)) (:background "#1B1E1C"))))
 '(diff-file-header ((((class color) (min-colors 257)) (:background "#242728" :foreground "#f8fbfc" :weight bold)) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#F5F5F5" :weight bold))))
 '(diff-refine-added ((((class color) (min-colors 257)) (:foreground "#242728" :background "#2AD043")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#87D700"))))
 '(diff-refine-changed ((((class color) (min-colors 257)) (:foreground "#242728" :background "#06d8ff")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#5FD7FF"))))
 '(diff-refine-removed ((((class color) (min-colors 257)) (:foreground "#242728" :background "#FF6159")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#FF1493"))))
 '(ediff-fine-diff-A ((((class color) (min-colors 257)) (:background "#A75B00")) (((class color) (min-colors 89)) (:background "#FFAF5F"))))
 '(ediff-fine-diff-B ((((class color) (min-colors 257)) (:background "#63de5d")) (((class color) (min-colors 89)) (:background "#AFD700"))))
 '(ediff-fine-diff-C ((((class color) (min-colors 257)) (:background "#9A8F21")) (((class color) (min-colors 89)) (:background "#FFFF87"))))
 '(ediff-current-diff-C ((((class color) (min-colors 257)) (:background "#1DB4D0")) (((class color) (min-colors 89)) (:background "#87D7FF"))))
 '(ediff-even-diff-A ((((class color) (min-colors 257)) (:background "#6A6D70" :foreground "#171A0B")) (((class color) (min-colors 89)) (:background "#8B8878" :foreground "#141414"))))
 '(ediff-odd-diff-A ((((class color) (min-colors 257)) (:background "#6A6D70" :foreground "#141414")) (((class color) (min-colors 89)) (:background "#8B8878" :foreground "#171A0B"))))
 '(ediff-even-diff-B ((((class color) (min-colors 257)) (:background "#6A6D70" :foreground "#141414")) (((class color) (min-colors 89)) (:background "#8B8878" :foreground "#171A0B"))))
 '(ediff-odd-diff-B ((((class color) (min-colors 257)) (:background "#6A6D70" :foreground "#171A0B")) (((class color) (min-colors 89)) (:background "#8B8878" :foreground "#141414"))))
 '(ediff-even-diff-C ((((class color) (min-colors 257)) (:background "#6A6D70" :foreground "#f8fbfc")) (((class color) (min-colors 89)) (:background "#8B8878" :foreground "#F5F5F5"))))
 '(ediff-odd-diff-C ((((class color) (min-colors 257)) (:background "#6A6D70" :foreground "#242728")) (((class color) (min-colors 89)) (:background "#8B8878" :foreground "#1B1E1C"))))
 '(flymake-errline ((((supports :underline (:style wave)) (class color) (min-colors 257)) (:underline (:style wave :color "#ff0066") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 257)) (:foreground "#FEB0CC" :background "#F20055" :weight bold :underline t)) (((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#FF1493") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#870000" :background "#FF5F87" :weight bold :underline t))))
 '(flymake-warnline ((((supports :underline (:style wave)) (class color) (min-colors 257)) (:underline (:style wave :color "#E6DB74") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 257)) (:foreground "#FFFACE" :background "#9A8F21" :weight bold :underline t)) (((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#CDC673") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#878700" :background "#FFFF87" :weight bold :underline t))))
 '(flycheck-error ((((supports :underline (:style wave)) (class color) (min-colors 257)) (:underline (:style wave :color "#ff0066") :inherit unspecified)) (((class color) (min-colors 257)) (:foreground "#FEB0CC" :background "#F20055" :weight bold :underline t)) (((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#FF1493") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#870000" :background "#FF5F87" :weight bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style wave)) (class color) (min-colors 257)) (:underline (:style wave :color "#E6DB74") :inherit unspecified)) (((class color) (min-colors 257)) (:foreground "#FFFACE" :background "#9A8F21" :weight bold :underline t)) (((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#CDC673") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#878700" :background "#FFFF87" :weight bold :underline t))))
 '(flycheck-info ((((supports :underline (:style wave)) (class color) (min-colors 257)) (:underline (:style wave :color "#06d8ff") :inherit unspecified)) (((class color) (min-colors 257)) (:foreground "#CAF5FD" :background "#1DB4D0" :weight bold :underline t)) (((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#5FD7FF") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#008787" :background "#87D7FF" :weight bold :underline t))))
 '(flycheck-fringe-error ((((class color) (min-colors 257)) (:foreground "#FEB0CC" :background "#F20055" :weight bold)) (((class color) (min-colors 89)) (:foreground "#870000" :background "#FF5F87" :weight bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 257)) (:foreground "#FFFACE" :background "#9A8F21" :weight bold)) (((class color) (min-colors 89)) (:foreground "#878700" :background "#FFFF87" :weight bold))))
 '(flycheck-fringe-info ((((class color) (min-colors 257)) (:foreground "#CAF5FD" :background "#1DB4D0" :weight bold)) (((class color) (min-colors 89)) (:foreground "#008787" :background "#87D7FF" :weight bold))))
 '(flyspell-duplicate ((((supports :underline (:style wave)) (class color) (min-colors 257)) (:underline (:style wave :color "#E6DB74") :inherit unspecified)) (((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold :underline t)) (((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#CDC673") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style wave)) (class color) (min-colors 257)) (:underline (:style wave :color "#ff0066") :inherit unspecified)) (((class color) (min-colors 257)) (:foreground "#ff0066" :weight bold :underline t)) (((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#FF1493") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold :underline t))))
 '(gnus-group-mail-1 ((((class color) (min-colors 257)) (:weight bold :inherit gnus-group-mail-1-empty)) (((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-1-empty))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 257)) (:inherit gnus-group-news-1-empty)) (((class color) (min-colors 89)) (:inherit gnus-group-news-1-empty))))
 '(gnus-group-mail-2 ((((class color) (min-colors 257)) (:weight bold :inherit gnus-group-mail-2-empty)) (((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-2-empty))))
 '(gnus-group-mail-2-empty ((((class color) (min-colors 257)) (:inherit gnus-group-news-2-empty)) (((class color) (min-colors 89)) (:inherit gnus-group-news-2-empty))))
 '(gnus-group-mail-3 ((((class color) (min-colors 257)) (:weight bold :inherit gnus-group-mail-3-empty)) (((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-3-empty))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 257)) (:inherit gnus-group-news-3-empty)) (((class color) (min-colors 89)) (:inherit gnus-group-news-3-empty))))
 '(gnus-group-mail-low ((((class color) (min-colors 257)) (:weight bold :inherit gnus-group-mail-low-empty)) (((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-low-empty))))
 '(gnus-group-mail-low-empty ((((class color) (min-colors 257)) (:inherit gnus-group-news-low-empty)) (((class color) (min-colors 89)) (:inherit gnus-group-news-low-empty))))
 '(gnus-group-news-1 ((((class color) (min-colors 257)) (:weight bold :inherit gnus-group-news-1-empty)) (((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-1-empty))))
 '(gnus-group-news-2 ((((class color) (min-colors 257)) (:weight bold :inherit gnus-group-news-2-empty)) (((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-2-empty))))
 '(gnus-group-news-3 ((((class color) (min-colors 257)) (:weight bold :inherit gnus-group-news-3-empty)) (((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-3-empty))))
 '(gnus-group-news-4 ((((class color) (min-colors 257)) (:weight bold :inherit gnus-group-news-4-empty)) (((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-4-empty))))
 '(gnus-group-news-5 ((((class color) (min-colors 257)) (:weight bold :inherit gnus-group-news-5-empty)) (((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-5-empty))))
 '(gnus-group-news-6 ((((class color) (min-colors 257)) (:weight bold :inherit gnus-group-news-6-empty)) (((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-6-empty))))
 '(gnus-group-news-low ((((class color) (min-colors 257)) (:weight bold :inherit gnus-group-news-low-empty)) (((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-low-empty))))
 '(gnus-header-content ((((class color) (min-colors 257)) (:inherit message-header-other)) (((class color) (min-colors 89)) (:inherit message-header-other))))
 '(gnus-header-from ((((class color) (min-colors 257)) (:inherit message-header-other)) (((class color) (min-colors 89)) (:inherit message-header-other))))
 '(gnus-header-name ((((class color) (min-colors 257)) (:inherit message-header-name)) (((class color) (min-colors 89)) (:inherit message-header-name))))
 '(gnus-header-newsgroups ((((class color) (min-colors 257)) (:inherit message-header-other)) (((class color) (min-colors 89)) (:inherit message-header-other))))
 '(gnus-header-subject ((((class color) (min-colors 257)) (:inherit message-header-subject)) (((class color) (min-colors 89)) (:inherit message-header-subject))))
 '(gnus-summary-cancelled ((((class color) (min-colors 257)) (:foreground "#ffac4a")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(gnus-summary-high-ancient ((((class color) (min-colors 257)) (:foreground "#06d8ff" :weight bold)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight bold))))
 '(gnus-summary-high-read ((((class color) (min-colors 257)) (:foreground "#63de5d" :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(gnus-summary-high-ticked ((((class color) (min-colors 257)) (:foreground "#ffac4a" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold))))
 '(gnus-summary-high-unread ((((class color) (min-colors 257)) (:foreground "#f8fbfc" :weight bold)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight bold))))
 '(gnus-summary-low-ancient ((((class color) (min-colors 257)) (:foreground "#06d8ff")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(gnus-summary-low-read ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(gnus-summary-low-ticked ((((class color) (min-colors 257)) (:foreground "#ffac4a")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(gnus-summary-low-unread ((((class color) (min-colors 257)) (:foreground "#f8fbfc")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(gnus-summary-normal-ancient ((((class color) (min-colors 257)) (:foreground "#06d8ff")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(gnus-summary-normal-read ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(gnus-summary-normal-ticked ((((class color) (min-colors 257)) (:foreground "#ffac4a")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(gnus-summary-normal-unread ((((class color) (min-colors 257)) (:foreground "#f8fbfc")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(gnus-summary-selected ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(gnus-group-news-1-empty ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(gnus-group-news-2-empty ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(gnus-group-news-4-empty ((((class color) (min-colors 257)) (:foreground "#06d8ff")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(gnus-group-news-5-empty ((((class color) (min-colors 257)) (:foreground "#06d8ff")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(gnus-group-news-6-empty ((((class color) (min-colors 257)) (:foreground "#1DB4D0")) (((class color) (min-colors 89)) (:foreground "#87D7FF"))))
 '(gnus-group-news-low-empty ((((class color) (min-colors 257)) (:foreground "#6A6D70")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(gnus-signature ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(helm-bookmark-directory ((((class color) (min-colors 257)) (:inherit helm-ff-directory)) (((class color) (min-colors 89)) (:inherit helm-ff-directory))))
 '(helm-bookmark-file ((((class color) (min-colors 257)) (:foreground "#f8fbfc")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(helm-bookmark-gnus ((((class color) (min-colors 257)) (:foreground "#53f2dc")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(helm-bookmark-info ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(helm-bookmark-man ((((class color) (min-colors 257)) (:foreground "#ab7eff")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(helm-bookmark-w3m ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(helm-buffer-file ((((class color) (min-colors 257)) (:foreground "#f8fbfc")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(helm-buffer-directory ((((class color) (min-colors 257)) (:foreground "#06d8ff")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(helm-buffer-process ((t (:foreground "gray"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 257)) (:foreground "#ff0066" :background "#242728" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :inverse-video t))))
 '(helm-buffer-size ((t (:foreground "gray"))))
 '(helm-candidate-number ((((class color) (min-colors 257)) (:background "#424748" :foreground "#ffffff" :bold t)) (((class color) (min-colors 89)) (:background "#474747" :foreground "#FFFAFA" :bold t))))
 '(helm-ff-directory ((((class color) (min-colors 257)) (:foreground "#06d8ff")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(helm-ff-executable ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(helm-ff-file ((((class color) (min-colors 257)) (:background "#242728" :foreground "#f8fbfc")) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#F5F5F5"))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 257)) (:background "#242728" :foreground "#ffac4a" :slant italic)) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#FF8C00" :slant italic))))
 '(helm-ff-prefix ((((class color) (min-colors 257)) (:background "#63de5d" :foreground "#242728")) (((class color) (min-colors 89)) (:background "#87D700" :foreground "#1B1E1C"))))
 '(helm-ff-symlink ((((class color) (min-colors 257)) (:foreground "#53f2dc")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(helm-grep-file ((((class color) (min-colors 257)) (:foreground "#53f2dc" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :underline t))))
 '(helm-grep-finish ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(helm-grep-lineno ((((class color) (min-colors 257)) (:foreground "#ffac4a")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(helm-grep-match ((((class color) (min-colors 257)) (:inherit helm-match))))
 '(helm-header ((((class color) (min-colors 257)) (:inherit header-line)) (((class color) (min-colors 89)) (:inherit terminal-header-line))))
 '(helm-lisp-completion-info ((((class color) (min-colors 257)) (:foreground "#f8fbfc")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(helm-lisp-show-completion ((((class color) (min-colors 257)) (:foreground "#E6DB74" :background "#424748" :bold t)) (((class color) (min-colors 89)) (:foreground "#CDC673" :background "#474747" :bold t))))
 '(helm-M-x-key ((((class color) (min-colors 257)) (:foreground "#ffac4a" :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :underline t))))
 '(helm-moccur-buffer ((((class color) (min-colors 257)) (:foreground "#53f2dc" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :underline t))))
 '(helm-match ((((class color) (min-colors 257)) (:foreground "#63de5d" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :inherit bold))))
 '(helm-match-item ((((class color) (min-colors 257)) (:inherit helm-match)) (((class color) (min-colors 89)) (:inherit helm-match))))
 '(helm-selection ((((class color) (min-colors 257)) (:background "#424748" :inherit bold :underline nil)) (((class color) (min-colors 89)) (:background "#474747" :inherit bold :underline nil))))
 '(helm-selection-line ((((class color) (min-colors 257)) (:background "#424748" :foreground "#ffffff" :underline nil)) (((class color) (min-colors 89)) (:background "#474747" :foreground "#FFFAFA" :underline nil))))
 '(helm-separator ((((class color) (min-colors 257)) (:foreground "#35393b")) (((class color) (min-colors 89)) (:foreground "#3D3D3D"))))
 '(helm-source-header ((((class color) (min-colors 257)) (:background "#C9ACFF" :foreground "#242728" :underline nil)) (((class color) (min-colors 89)) (:background "#AF87D7" :foreground "#1B1E1C" :underline nil))))
 '(helm-swoop-target-line-face ((((class color) (min-colors 257)) (:background "#424748")) (((class color) (min-colors 89)) (:background "#474747"))))
 '(helm-swoop-target-line-block-face ((((class color) (min-colors 257)) (:background "#424748")) (((class color) (min-colors 89)) (:background "#474747"))))
 '(helm-swoop-target-word-face ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(helm-visible-mark ((((class color) (min-colors 257)) (:background "#242728" :foreground "#ff8eff" :bold t)) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#D700D7" :bold t))))
 '(highlight-indentation-face ((((class color) (min-colors 257)) (:background "#35393b")) (((class color) (min-colors 89)) (:background "#3D3D3D"))))
 '(highlight-indentation-current-column-face ((((class color) (min-colors 257)) (:background "#35393b")) (((class color) (min-colors 89)) (:background "#3D3D3D"))))
 '(hl-line ((((class color) (min-colors 257)) (:background "#424748")) (((class color) (min-colors 89)) (:background "#474747"))))
 '(ido-first-match ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(ido-only-match ((((class color) (min-colors 257)) (:foreground "#242728" :background "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#CDC673" :weight normal))))
 '(ido-subdir ((((class color) (min-colors 257)) (:foreground "#06d8ff")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(ido-incomplete-regexp ((((class color) (min-colors 257)) (:foreground "#ff0066" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(ido-indicator ((((class color) (min-colors 257)) (:background "#ff0066" :foreground "#242728" :width condensed)) (((class color) (min-colors 89)) (:background "#FF1493" :foreground "#1B1E1C" :width condensed))))
 '(ido-virtual ((((class color) (min-colors 257)) (:foreground "#53f2dc")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(linum ((t (:background "#2B2F31" :foreground "dark gray"))))
 '(magit-diff-added ((((class color) (min-colors 257)) (:foreground "#2AD043" :background "#242728")) (((class color) (min-colors 89)) (:foreground "#87D700" :background "#1B1E1C"))))
 '(magit-diff-added-highlight ((((class color) (min-colors 257)) (:foreground "#2AD043" :background "#424748")) (((class color) (min-colors 89)) (:foreground "#87D700" :background "#474747"))))
 '(magit-diff-removed ((((class color) (min-colors 257)) (:foreground "#FF6159" :background "#242728")) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C"))))
 '(magit-diff-removed-highlight ((((class color) (min-colors 257)) (:foreground "#FF6159" :background "#424748")) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#474747"))))
 '(magit-cherry-equivalent ((((class color) (min-colors 257)) (:foreground "#ff8eff")) (((class color) (min-colors 89)) (:foreground "#D700D7"))))
 '(magit-cherry-unmatched ((((class color) (min-colors 257)) (:foreground "#53f2dc")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(magit-head ((((class color) (min-colors 257)) (:foreground "#ab7eff")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(magit-branch-local ((((class color) (min-colors 257)) (:foreground "#ab7eff")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(magit-branch-remote ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(magit-section-heading ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(magit-process-ok ((((class color) (min-colors 257)) (:foreground "#2AD043" :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(magit-process-ng ((((class color) (min-colors 257)) (:foreground "#FF6159" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(magit-log-author ((((class color) (min-colors 257)) (:foreground "#53f2dc")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(magit-log-graph ((t (:foreground "gray"))))
 '(magit-reflog-amend ((((class color) (min-colors 257)) (:foreground "#ab7eff")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(magit-reflog-rebase ((((class color) (min-colors 257)) (:foreground "#ab7eff")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(magit-reflog-checkout ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(magit-reflog-reset ((((class color) (min-colors 257)) (:foreground "#FF6159")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(magit-reflog-commit ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(magit-reflog-merge ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(magit-reflog-cherry-pick ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(magit-reflog-other ((((class color) (min-colors 257)) (:foreground "#53f2dc")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(magit-reflog-remote ((((class color) (min-colors 257)) (:foreground "#53f2dc")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(monky-section-title ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(monky-diff-title ((((class color) (min-colors 257)) (:foreground "#BBF7EF" :background "#383c3d")) (((class color) (min-colors 89)) (:foreground "#AFFFFF" :background "#333333"))))
 '(monky-diff-add ((((class color) (min-colors 257)) (:foreground "#2AD043")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(monky-diff-del ((((class color) (min-colors 257)) (:foreground "#FF6159")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(markdown-header-face ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(markdown-header-face-1 ((((class color) (min-colors 257)) (:inherit markdown-header-face :height 1.3)) (((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.3))))
 '(markdown-header-face-2 ((((class color) (min-colors 257)) (:inherit markdown-header-face :height 1.2)) (((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.2))))
 '(markdown-header-face-3 ((((class color) (min-colors 257)) (:inherit markdown-header-face :height 1.15)) (((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.15))))
 '(markdown-header-face-4 ((((class color) (min-colors 257)) (:inherit markdown-header-face :height 1.1)) (((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.1))))
 '(markdown-header-face-5 ((((class color) (min-colors 257)) (:inherit markdown-header-face)) (((class color) (min-colors 89)) (:inherit markdown-header-face))))
 '(markdown-header-face-6 ((((class color) (min-colors 257)) (:inherit markdown-header-face)) (((class color) (min-colors 89)) (:inherit markdown-header-face))))
 '(message-cited-text ((t (:foreground "gray"))))
 '(message-header-name ((t (:foreground "gray"))))
 '(message-header-other ((((class color) (min-colors 257)) (:foreground "#f8fbfc" :weight normal)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(message-header-to ((((class color) (min-colors 257)) (:foreground "#f8fbfc" :weight normal)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(message-header-cc ((((class color) (min-colors 257)) (:foreground "#f8fbfc" :weight normal)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(message-header-newsgroups ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(message-header-subject ((((class color) (min-colors 257)) (:foreground "#53f2dc" :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :weight normal))))
 '(message-header-xheader ((((class color) (min-colors 257)) (:foreground "#53f2dc")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(message-mml ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(message-separator ((t (:foreground "gray" :slant italic))))
 '(mu4e-cited-1-face ((((class color) (min-colors 257)) (:foreground "#63de5d" :slant italic :weight normal)) (((class color) (min-colors 89)) (:foreground "#87D700" :slant italic :weight normal))))
 '(mu4e-cited-2-face ((((class color) (min-colors 257)) (:foreground "#06d8ff" :slant italic :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :slant italic :weight normal))))
 '(mu4e-cited-3-face ((((class color) (min-colors 257)) (:foreground "#ffac4a" :slant italic :weight normal)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :slant italic :weight normal))))
 '(mu4e-cited-4-face ((((class color) (min-colors 257)) (:foreground "#E6DB74" :slant italic :weight normal)) (((class color) (min-colors 89)) (:foreground "#CDC673" :slant italic :weight normal))))
 '(mu4e-cited-5-face ((((class color) (min-colors 257)) (:foreground "#53f2dc" :slant italic :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :slant italic :weight normal))))
 '(mu4e-cited-6-face ((((class color) (min-colors 257)) (:foreground "#63de5d" :slant italic :weight normal)) (((class color) (min-colors 89)) (:foreground "#87D700" :slant italic :weight normal))))
 '(mu4e-cited-7-face ((((class color) (min-colors 257)) (:foreground "#06d8ff" :slant italic :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :slant italic :weight normal))))
 '(mu4e-flagged-face ((((class color) (min-colors 257)) (:foreground "#ff8eff" :weight bold)) (((class color) (min-colors 89)) (:foreground "#D700D7" :weight bold))))
 '(mu4e-warning-face ((((class color) (min-colors 257)) (:foreground "#ff0066" :slant normal :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF1493" :slant normal :weight bold))))
 '(mu4e-header-highlight-face ((((class color) (min-colors 257)) (:inherit unspecified :foreground unspecified :background "#424748" :underline "#ffffff" :weight normal)) (((class color) (min-colors 89)) (:inherit unspecified :foreground unspecified :background "#474747" :underline "#FFFAFA" :weight normal))))
 '(mu4e-draft-face ((((class color) (min-colors 257)) (:inherit font-lock-string-face)) (((class color) (min-colors 89)) (:inherit font-lock-string-face))))
 '(mu4e-footer-face ((((class color) (min-colors 257)) (:inherit font-lock-comment-face)) (((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(mu4e-forwarded-face ((((class color) (min-colors 257)) (:inherit font-lock-builtin-face :weight normal)) (((class color) (min-colors 89)) (:inherit font-lock-builtin-face :weight normal))))
 '(mu4e-header-face ((((class color) (min-colors 257)) (:inherit default)) (((class color) (min-colors 89)) (:inherit default))))
 '(mu4e-header-marks-face ((((class color) (min-colors 257)) (:inherit font-lock-preprocessor-face)) (((class color) (min-colors 89)) (:inherit font-lock-preprocessor-face))))
 '(mu4e-header-title-face ((((class color) (min-colors 257)) (:inherit font-lock-type-face)) (((class color) (min-colors 89)) (:inherit font-lock-type-face))))
 '(mu4e-highlight-face ((((class color) (min-colors 257)) (:inherit font-lock-pseudo-keyword-face :weight bold)) (((class color) (min-colors 89)) (:inherit font-lock-pseudo-keyword-face :weight bold))))
 '(mu4e-moved-face ((((class color) (min-colors 257)) (:inherit font-lock-comment-face :slant italic)) (((class color) (min-colors 89)) (:inherit font-lock-comment-face :slant italic))))
 '(mu4e-ok-face ((((class color) (min-colors 257)) (:inherit font-lock-comment-face :slant normal :weight bold)) (((class color) (min-colors 89)) (:inherit font-lock-comment-face :slant normal :weight bold))))
 '(mu4e-replied-face ((((class color) (min-colors 257)) (:inherit font-lock-builtin-face :weight normal)) (((class color) (min-colors 89)) (:inherit font-lock-builtin-face :weight normal))))
 '(mu4e-system-face ((((class color) (min-colors 257)) (:inherit font-lock-comment-face :slant italic)) (((class color) (min-colors 89)) (:inherit font-lock-comment-face :slant italic))))
 '(mu4e-title-face ((((class color) (min-colors 257)) (:inherit font-lock-type-face :weight bold)) (((class color) (min-colors 89)) (:inherit font-lock-type-face :weight bold))))
 '(mu4e-trashed-face ((((class color) (min-colors 257)) (:inherit font-lock-comment-face :strike-through t)) (((class color) (min-colors 89)) (:inherit font-lock-comment-face :strike-through t))))
 '(mu4e-unread-face ((((class color) (min-colors 257)) (:inherit font-lock-keyword-face :weight bold)) (((class color) (min-colors 89)) (:inherit font-lock-keyword-face :weight bold))))
 '(neo-banner-face ((((class color) (min-colors 257)) (:foreground "#06d8ff" :background "#242728" :weight bold)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :background "#1B1E1C" :weight bold))))
 '(neo-header-face ((((class color) (min-colors 257)) (:foreground "#ffffff" :background "#242728")) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#1B1E1C"))))
 '(neo-root-dir-face ((((class color) (min-colors 257)) (:foreground "#63de5d" :background "#242728")) (((class color) (min-colors 89)) (:foreground "#87D700" :background "#1B1E1C"))))
 '(neo-dir-link-face ((((class color) (min-colors 257)) (:foreground "#06d8ff")) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :background "#1B1E1C"))))
 '(neo-file-link-face ((((class color) (min-colors 257)) (:foreground "#f8fbfc")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(neo-button-face ((((class color) (min-colors 257)) (:underline nil)) (((class color) (min-colors 89)) (:underline nil))))
 '(neo-expand-btn-face ((((class color) (min-colors 257)) (:foreground "#6A6D70")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(neo-vc-default-face ((((class color) (min-colors 257)) (:foreground "#f8fbfc")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(neo-vc-user-face ((((class color) (min-colors 257)) (:foreground "#ff0066" :slant italic)) (((class color) (min-colors 89)) (:foreground "#FF1493" :slant italic))))
 '(neo-vc-up-to-date-face ((((class color) (min-colors 257)) (:foreground "#6A6D70")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(neo-vc-edited-face ((((class color) (min-colors 257)) (:foreground "#ffac4a")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(neo-vc-needs-update-face ((((class color) (min-colors 257)) (:underline t)) (((class color) (min-colors 89)) (:underline t))))
 '(neo-vc-needs-merge-face ((((class color) (min-colors 257)) (:foreground "#ff0066")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(neo-vc-unlocked-changes-face ((((class color) (min-colors 257)) (:foreground "#ff0066" :background "#6A6D70")) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#8B8878"))))
 '(neo-vc-added-face ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(neo-vc-removed-face ((((class color) (min-colors 257)) (:strike-through t)) (((class color) (min-colors 89)) (:strike-through t))))
 '(neo-vc-conflict-face ((((class color) (min-colors 257)) (:foreground "#ff0066")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(neo-vc-missing-face ((((class color) (min-colors 257)) (:foreground "#ff0066")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(neo-vc-ignored-face ((((class color) (min-colors 257)) (:foreground "#6A6D70")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-agenda-structure ((((class color) (min-colors 257)) (:foreground "#ffffff" :background "#424748" :weight bold :slant normal :inverse-video nil :height 1.1 :underline nil :box (:line-width 2 :color "#242728"))) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#474747" :weight bold :slant normal :inverse-video nil :height 1.1 :underline nil :box (:line-width 2 :color "#1B1E1C")))))
 '(org-agenda-calendar-event ((((class color) (min-colors 257)) (:foreground "#ffffff")) (((class color) (min-colors 89)) (:foreground "#FFFAFA"))))
 '(org-agenda-calendar-sexp ((((class color) (min-colors 257)) (:foreground "#f8fbfc" :slant italic)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :slant italic))))
 '(org-agenda-date ((((class color) (min-colors 257)) (:foreground "#6A6D70" :background "#242728" :weight normal :inverse-video nil :overline nil :slant normal :height 1.0 :box (:line-width 2 :color "#242728"))) (((class color) (min-colors 89)) (:foreground "#8B8878" :background "#1B1E1C" :weight normal :inverse-video nil :overline nil :slant normal :height 1.0 :box (:line-width 2 :color "#1B1E1C")))))
 '(org-agenda-date-weekend ((((class color) (min-colors 257)) (:inherit org-agenda-date :inverse-video nil :background unspecified :foreground "#6A6D70" :weight unspecified :underline t :overline nil :box unspecified)) (((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video nil :background unspecified :foreground "#8B8878" :weight unspecified :underline t :overline nil :box unspecified))))
 '(org-agenda-date-today ((((class color) (min-colors 257)) (:inherit org-agenda-date :inverse-video t :weight bold :underline unspecified :overline nil :box unspecified :foreground "#06d8ff" :background "#242728")) (((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video t :weight bold :underline unspecified :overline nil :box unspecified :foreground "#5FD7FF" :background "#1B1E1C"))))
 '(org-agenda-done ((((class color) (min-colors 257)) (:foreground "#6A6D70" :slant italic)) (((class color) (min-colors 89)) (:foreground "#8B8878" :slant italic))))
 '(org-archived ((((class color) (min-colors 257)) (:foreground "#6A6D70" :weight normal)) (((class color) (min-colors 89)) (:foreground "#8B8878" :weight normal))))
 '(org-block ((((class color) (min-colors 257)) (:foreground "#6A6D70")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-block-begin-line ((((class color) (min-colors 257)) (:foreground "#6A6D70" :slant italic)) (((class color) (min-colors 89)) (:foreground "#8B8878" :slant italic))))
 '(org-checkbox ((((class color) (min-colors 257)) (:background "#35393b" :foreground "#ab7eff" :box nil)) (((class color) (min-colors 89)) (:background "#3D3D3D" :foreground "#AF87FF" :box nil))))
 '(org-code ((((class color) (min-colors 257)) (:foreground "#6A6D70")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-date ((((class color) (min-colors 257)) (:foreground "#06d8ff" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))
 '(org-done ((((class color) (min-colors 257)) (:weight bold :foreground "#63de5d")) (((class color) (min-colors 89)) (:weight bold :foreground "#87D700"))))
 '(org-ellipsis ((((class color) (min-colors 257)) (:foreground "#6A6D70")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-formula ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(org-headline-done ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(org-hide ((((class color) (min-colors 257)) (:foreground "#242728")) (((class color) (min-colors 89)) (:foreground "#1B1E1C"))))
 '(org-level-1 ((((class color) (min-colors 257)) (:inherit variable-pitch :height 1.3 :foreground "#ffac4a")) (((class color) (min-colors 89)) (:inherit variable-pitch :height 1.3 :foreground "#FF8C00"))))
 '(org-level-2 ((((class color) (min-colors 257)) (:inherit variable-pitch :height 1.2 :foreground "#63de5d")) (((class color) (min-colors 89)) (:inherit variable-pitch :height 1.2 :foreground "#87D700"))))
 '(org-level-3 ((((class color) (min-colors 257)) (:inherit variable-pitch :height 1.15 :foreground "#06d8ff")) (((class color) (min-colors 89)) (:inherit variable-pitch :height 1.15 :foreground "#5FD7FF"))))
 '(org-level-4 ((((class color) (min-colors 257)) (:inherit variable-pitch :height 1.1 :foreground "#E6DB74")) (((class color) (min-colors 89)) (:inherit variable-pitch :height 1.1 :foreground "#CDC673"))))
 '(org-level-5 ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#53f2dc")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FFFFF"))))
 '(org-level-6 ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#63de5d")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#87D700"))))
 '(org-level-7 ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#ff0066")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#FF1493"))))
 '(org-level-8 ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#06d8ff")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FD7FF"))))
 '(org-link ((((class color) (min-colors 257)) (:foreground "#E6DB74" :underline t)) (((class color) (min-colors 89)) (:foreground "#CDC673" :underline t))))
 '(org-sexp-date ((((class color) (min-colors 257)) (:foreground "#ab7eff")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(org-scheduled ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(org-scheduled-previously ((((class color) (min-colors 257)) (:foreground "#53f2dc")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(org-scheduled-today ((((class color) (min-colors 257)) (:foreground "#06d8ff" :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight normal))))
 '(org-special-keyword ((((class color) (min-colors 257)) (:foreground "#6A6D70" :weight bold)) (((class color) (min-colors 89)) (:foreground "#8B8878" :weight bold))))
 '(org-table ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(org-tag ((((class color) (min-colors 257)) (:weight bold)) (((class color) (min-colors 89)) (:weight bold))))
 '(org-time-grid ((((class color) (min-colors 257)) (:foreground "#6A6D70")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-todo ((((class color) (min-colors 257)) (:foreground "#ff0066" :weight bold))))
 '(org-upcoming-deadline ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal :underline nil)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal :underline nil))))
 '(org-warning ((((class color) (min-colors 257)) (:foreground "#ffac4a" :weight normal :underline nil)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight normal :underline nil))))
 '(org-habit-clear-face ((((class color) (min-colors 257)) (:background "#1DB4D0" :foreground "#CAF5FD")) (((class color) (min-colors 89)) (:background "#87D7FF" :foreground "#008787"))))
 '(org-habit-clear-future-face ((((class color) (min-colors 257)) (:background "#1DB4D0")) (((class color) (min-colors 89)) (:background "#87D7FF"))))
 '(org-habit-ready-face ((((class color) (min-colors 257)) (:background "#63de5d" :foreground "#63de5d")) (((class color) (min-colors 89)) (:background "#AFD700" :foreground "#87D700"))))
 '(org-habit-ready-future-face ((((class color) (min-colors 257)) (:background "#63de5d")) (((class color) (min-colors 89)) (:background "#AFD700"))))
 '(org-habit-alert-face ((((class color) (min-colors 257)) (:background "#E6DB74" :foreground "#9A8F21")) (((class color) (min-colors 89)) (:background "#CDC673" :foreground "#FFFF87"))))
 '(org-habit-alert-future-face ((((class color) (min-colors 257)) (:background "#9A8F21")) (((class color) (min-colors 89)) (:background "#FFFF87"))))
 '(org-habit-overdue-face ((((class color) (min-colors 257)) (:background "#ff0066" :foreground "#F20055")) (((class color) (min-colors 89)) (:background "#FF1493" :foreground "#FF5F87"))))
 '(org-habit-overdue-future-face ((((class color) (min-colors 257)) (:background "#F20055")) (((class color) (min-colors 89)) (:background "#FF5F87"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 257)) (:foreground "#6A6D70")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 257)) (:background "#E6DB74")) (((class color) (min-colors 89)) (:background "#CDC673"))))
 '(org-clock-overlay ((((class color) (min-colors 257)) (:background "#E6DB74")) (((class color) (min-colors 89)) (:background "#CDC673"))))
 '(org-column ((((class color) (min-colors 257)) (:background "#424748" :strike-through nil :underline nil :slant normal :weight normal :inherit default)) (((class color) (min-colors 89)) (:background "#474747" :strike-through nil :underline nil :slant normal :weight normal :inherit default))))
 '(org-column-title ((((class color) (min-colors 257)) (:background "#424748" :underline t :weight bold)) (((class color) (min-colors 89)) (:background "#474747" :underline t :weight bold))))
 '(org-date-selected ((((class color) (min-colors 257)) (:foreground "#ff0066" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :inverse-video t))))
 '(org-document-info ((((class color) (min-colors 257)) (:foreground "#f8fbfc")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(org-document-title ((((class color) (min-colors 257)) (:foreground "#ffffff" :weight bold :height 1.3)) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :weight bold :height 1.3))))
 '(org-drawer ((((class color) (min-colors 257)) (:foreground "#53f2dc")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(org-footnote ((((class color) (min-colors 257)) (:foreground "#ff8eff" :underline t)) (((class color) (min-colors 89)) (:foreground "#D700D7" :underline t))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 257)) (:inherit mode-line)) (((class color) (min-colors 89)) (:inherit mode-line))))
 '(outline-1 ((((class color) (min-colors 257)) (:inherit org-level-1)) (((class color) (min-colors 89)) (:inherit org-level-1))))
 '(outline-2 ((((class color) (min-colors 257)) (:inherit org-level-2)) (((class color) (min-colors 89)) (:inherit org-level-2))))
 '(outline-3 ((((class color) (min-colors 257)) (:inherit org-level-3)) (((class color) (min-colors 89)) (:inherit org-level-3))))
 '(outline-4 ((((class color) (min-colors 257)) (:inherit org-level-4)) (((class color) (min-colors 89)) (:inherit org-level-4))))
 '(outline-5 ((((class color) (min-colors 257)) (:inherit org-level-5)) (((class color) (min-colors 89)) (:inherit org-level-5))))
 '(outline-6 ((((class color) (min-colors 257)) (:inherit org-level-6)) (((class color) (min-colors 89)) (:inherit org-level-6))))
 '(outline-7 ((((class color) (min-colors 257)) (:inherit org-level-7)) (((class color) (min-colors 89)) (:inherit org-level-7))))
 '(outline-8 ((((class color) (min-colors 257)) (:inherit org-level-8)) (((class color) (min-colors 89)) (:inherit org-level-8))))
 '(popup-face ((((class color) (min-colors 257)) (:background "#424748" :foreground "#f8fbfc")) (((class color) (min-colors 89)) (:background "#474747" :foreground "#F5F5F5"))))
 '(popup-isearch-match ((((class color) (min-colors 257)) (:background "#63de5d")) (((class color) (min-colors 89)) (:background "#87D700"))))
 '(popup-menu-face ((((class color) (min-colors 257)) (:background "#424748" :foreground "#f8fbfc")) (((class color) (min-colors 89)) (:background "#474747" :foreground "#F5F5F5"))))
 '(popup-menu-mouse-face ((((class color) (min-colors 257)) (:background "#06d8ff" :foreground "#f8fbfc")) (((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#F5F5F5"))))
 '(popup-menu-selection-face ((((class color) (min-colors 257)) (:background "#ff8eff" :foreground "#242728")) (((class color) (min-colors 89)) (:background "#D700D7" :foreground "#1B1E1C"))))
 '(popup-scroll-bar-background-face ((((class color) (min-colors 257)) (:background "#6A6D70")) (((class color) (min-colors 89)) (:background "#8B8878"))))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 257)) (:background "#ffffff")) (((class color) (min-colors 89)) (:background "#FFFAFA"))))
 '(popup-tip-face ((((class color) (min-colors 257)) (:background "#424748" :foreground "#f8fbfc")) (((class color) (min-colors 89)) (:background "#474747" :foreground "#F5F5F5"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 257)) (:foreground "#ab7eff")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 257)) (:foreground "#06d8ff")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 257)) (:foreground "#ffac4a")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 257)) (:foreground "#ff0066")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 257)) (:foreground "#FF61FF")) (((class color) (min-colors 89)) (:foreground "#D700D7"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 257)) (:foreground "#ab7eff")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 257)) (:foreground "#06d8ff")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 257)) (:foreground "#f8fbfc" :background "#242728" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C" :inverse-video t))))
 '(sh-quoted-exec ((((class color) (min-colors 257)) (:foreground "#ab7eff" :weight bold)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :weight bold))))
 '(sh-escaped-newline ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(sh-heredoc ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(sp-pair-overlay-face ((((class color) (min-colors 257)) (:background "#424748")) (((class color) (min-colors 89)) (:background "#474747"))))
 '(sp-wrap-overlay-face ((((class color) (min-colors 257)) (:background "#424748")) (((class color) (min-colors 89)) (:background "#474747"))))
 '(sp-wrap-tag-overlay-face ((((class color) (min-colors 257)) (:background "#424748")) (((class color) (min-colors 89)) (:background "#474747"))))
 '(sp-show-pair-enclosing ((((class color) (min-colors 257)) (:inherit highlight)) (((class color) (min-colors 89)) (:inherit highlight))))
 '(sp-show-pair-match-face ((((class color) (min-colors 257)) (:background "#BBF7EF" :foreground "#00b2ac" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#87D700" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(sp-show-pair-mismatch-face ((((class color) (min-colors 257)) (:foreground "#ff0066" :background "#242728" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(show-paren-match ((((class color) (min-colors 257)) (:foreground "#00b2ac" :background "#BBF7EF" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#5FAFAF" :background "#AFFFFF" :weight normal :inverse-video t))))
 '(show-paren-mismatch ((((class color) (min-colors 257)) (:foreground "#ff0066" :background "#242728" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(speedbar-button-face ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#6A6D70")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#8B8878"))))
 '(speedbar-directory-face ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#06d8ff")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FD7FF"))))
 '(speedbar-file-face ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#f8fbfc")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#F5F5F5"))))
 '(speedbar-highlight-face ((((class color) (min-colors 257)) (:inherit variable-pitch :background "#424748")) (((class color) (min-colors 89)) (:inherit variable-pitch :background "#474747"))))
 '(speedbar-selected-face ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#E6DB74" :underline t)) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#CDC673" :underline t))))
 '(speedbar-separator-face ((((class color) (min-colors 257)) (:inherit variable-pitch :background "#06d8ff" :foreground "#242728" :overline "#4BBEAE")) (((class color) (min-colors 89)) (:inherit variable-pitch :background "#5FD7FF" :foreground "#1B1E1C" :overline "#AFFFFF"))))
 '(speedbar-tag-face ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#63de5d")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#87D700"))))
 '(table-cell ((((class color) (min-colors 257)) (:foreground "#f8fbfc" :background "#424748")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#474747"))))
 '(tooltip ((((class color) (min-colors 257)) (:background "#242728" :foreground "#E6DB74" :inherit variable-pitch))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 257)) (:foreground "#6A6D70" :background "#242728")) (((class color) (min-colors 89)) (:foreground "#8B8878" :background "#1B1E1C"))))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 257)) (:foreground "#63de5d")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 257)) (:foreground "#06d8ff" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :inverse-video t))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 257)) (:foreground "#ffffff" :background "#242728" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#1B1E1C" :weight bold))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(default ((((class color) (min-colors 257)) (:foreground "#f8fbfc" :background "#242728")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C")))))

(provide-theme 'darkokai-custom)
